export const PRODUCT_TYPES = {
  perfume: {
    productType: "perfume",
    label: "Perfume",
    variantType: "perfume-volume",
    variantLabel: "Volume",
    variantPresets: ["30ml", "50ml", "100ml"],
    shopSubtitle: "Explore our collection of luxury fragrances",
    heroFallback: {
      title: "Discover Your Signature Scent",
      subtitle: "Curated luxury perfumes crafted for the discerning",
      cta: "Shop Collection",
    },
    homeSections: ["hero", "featured", "categories", "newArrivals", "promo"],
    enableSizeFilter: false,
  },
  fashion: {
    productType: "fashion",
    label: "Fashion",
    variantType: "fashion-size",
    variantLabel: "Size",
    variantPresets: ["S", "M", "L", "XL", "XXL"],
    shopSubtitle: "Explore our latest fashion collection",
    heroFallback: {
      title: "New Season Essentials",
      subtitle: "Modern streetwear and timeless wardrobe staples",
      cta: "Shop New Collection",
    },
    homeSections: [
      "hero",
      "newCollection",
      "featured",
      "bestSellers",
      "categories",
      "newsletter",
    ],
    enableSizeFilter: true,
  },
};

export const DEFAULT_PRODUCT_TYPE = "perfume";

export function getProductTypeConfig(productType) {
  return PRODUCT_TYPES[productType] ?? PRODUCT_TYPES[DEFAULT_PRODUCT_TYPE];
}

export function resolvePlatformConfig(platform = {}) {
  const productType = platform.productType ?? DEFAULT_PRODUCT_TYPE;
  return {
    productType,
    ...getProductTypeConfig(productType),
  };
}

export function buildVariantRows(presets, basePrice, skuPrefix, stockPattern = []) {
  return presets.map((label, index) => ({
    label,
    price: basePrice + index * 5,
    stock: stockPattern[index] ?? 12 + index * 3,
    sku: `${skuPrefix}-${label}`,
  }));
}

export function productWithVariants({
  id,
  name,
  description,
  categoryId,
  coverSeed,
  gallerySeeds = [],
  tags,
  basePrice,
  skuPrefix,
  stockPattern,
  variantPresets,
}) {
  const presets = variantPresets ?? ["S", "M", "L", "XL", "XXL"];
  const variants = buildVariantRows(presets, basePrice, skuPrefix, stockPattern);

  return {
    id,
    name,
    description,
    coverImage: `https://picsum.photos/seed/${coverSeed}/600/750`,
    gallery: gallerySeeds.map(
      (seed, index) => `https://picsum.photos/seed/${seed}/${600 + index * 10}/750`
    ),
    categoryId,
    variantType: "fashion-size",
    variantLabel: "Size",
    lowStockThreshold: 5,
    variants,
    sizes: variants.map((v) => ({
      size: v.label,
      price: v.price,
      stock: v.stock,
      sku: v.sku,
    })),
    tags,
  };
}

export function getFashionDemoCategories() {
  return [
    {
      id: 1,
      name: "T-Shirts",
      slug: "t-shirts",
      description: "Everyday tees and statement tops",
      image: null,
      sortOrder: 1,
      active: true,
    },
    {
      id: 2,
      name: "Hoodies",
      slug: "hoodies",
      description: "Cozy hoodies for every season",
      image: null,
      sortOrder: 2,
      active: true,
    },
    {
      id: 3,
      name: "Jackets",
      slug: "jackets",
      description: "Layer up with premium outerwear",
      image: null,
      sortOrder: 3,
      active: true,
    },
    {
      id: 4,
      name: "Pants",
      slug: "pants",
      description: "Tailored and relaxed bottoms",
      image: null,
      sortOrder: 4,
      active: true,
    },
    {
      id: 5,
      name: "Shorts",
      slug: "shorts",
      description: "Warm-weather essentials",
      image: null,
      sortOrder: 5,
      active: true,
    },
    {
      id: 6,
      name: "Accessories",
      slug: "accessories",
      description: "Finish the look",
      image: null,
      sortOrder: 6,
      active: true,
    },
  ];
}

export function getFashionDemoProducts() {
  const sizes = ["S", "M", "L", "XL", "XXL"];

  return [
    productWithVariants({
      id: 1,
      name: "Oversized Black T-Shirt",
      description: "Relaxed-fit cotton tee with a soft washed finish.",
      categoryId: 1,
      coverSeed: "fashion-black-tee",
      gallerySeeds: ["fashion-black-tee-2", "fashion-black-tee-3"],
      tags: ["new", "bestseller"],
      basePrice: 29,
      skuPrefix: "OBT",
      stockPattern: [18, 24, 20, 14, 10],
      variantPresets: sizes,
    }),
    productWithVariants({
      id: 2,
      name: "Basic White T-Shirt",
      description: "Classic crew neck tee in premium heavyweight cotton.",
      categoryId: 1,
      coverSeed: "fashion-white-tee",
      gallerySeeds: ["fashion-white-tee-2"],
      tags: ["essentials"],
      basePrice: 24,
      skuPrefix: "BWT",
      stockPattern: [30, 28, 25, 18, 12],
      variantPresets: sizes,
    }),
    productWithVariants({
      id: 3,
      name: "Striped Crew Neck Tee",
      description: "Breton-inspired stripes with a modern slim profile.",
      categoryId: 1,
      coverSeed: "fashion-striped-tee",
      tags: ["new"],
      basePrice: 32,
      skuPrefix: "SCT",
      variantPresets: sizes,
    }),
    productWithVariants({
      id: 4,
      name: "Graphic Logo Tee",
      description: "Bold front graphic on ultra-soft jersey fabric.",
      categoryId: 1,
      coverSeed: "fashion-graphic-tee",
      tags: ["limited"],
      basePrice: 34,
      skuPrefix: "GLT",
      variantPresets: sizes,
    }),
    productWithVariants({
      id: 5,
      name: "Essential Hoodie",
      description: "Midweight fleece hoodie with kangaroo pocket.",
      categoryId: 2,
      coverSeed: "fashion-essential-hoodie",
      gallerySeeds: ["fashion-essential-hoodie-2"],
      tags: ["bestseller", "new"],
      basePrice: 59,
      skuPrefix: "EH",
      stockPattern: [15, 22, 18, 12, 8],
      variantPresets: sizes,
    }),
    productWithVariants({
      id: 6,
      name: "Zip-Up Hoodie",
      description: "Full-zip hoodie with ribbed cuffs and matte hardware.",
      categoryId: 2,
      coverSeed: "fashion-zip-hoodie",
      tags: ["essentials"],
      basePrice: 64,
      skuPrefix: "ZH",
      variantPresets: sizes,
    }),
    productWithVariants({
      id: 7,
      name: "Oversized Fleece Hoodie",
      description: "Dropped shoulders and brushed interior for all-day comfort.",
      categoryId: 2,
      coverSeed: "fashion-oversized-hoodie",
      tags: ["new"],
      basePrice: 68,
      skuPrefix: "OFH",
      variantPresets: sizes,
    }),
    productWithVariants({
      id: 8,
      name: "Classic Pullover Hoodie",
      description: "Everyday pullover with tonal embroidery detail.",
      categoryId: 2,
      coverSeed: "fashion-pullover-hoodie",
      tags: ["bestseller"],
      basePrice: 55,
      skuPrefix: "CPH",
      variantPresets: sizes,
    }),
    productWithVariants({
      id: 9,
      name: "Denim Jacket",
      description: "Vintage-wash denim jacket with metal button closure.",
      categoryId: 3,
      coverSeed: "fashion-denim-jacket",
      gallerySeeds: ["fashion-denim-jacket-2", "fashion-denim-jacket-3"],
      tags: ["bestseller", "new"],
      basePrice: 89,
      skuPrefix: "DJ",
      stockPattern: [10, 14, 12, 8, 5],
      variantPresets: sizes,
    }),
    productWithVariants({
      id: 10,
      name: "Bomber Jacket",
      description: "Lightweight nylon bomber with ribbed trim.",
      categoryId: 3,
      coverSeed: "fashion-bomber-jacket",
      tags: ["new"],
      basePrice: 95,
      skuPrefix: "BJ",
      variantPresets: sizes,
    }),
    productWithVariants({
      id: 11,
      name: "Lightweight Windbreaker",
      description: "Packable shell with water-resistant finish.",
      categoryId: 3,
      coverSeed: "fashion-windbreaker",
      tags: ["essentials"],
      basePrice: 79,
      skuPrefix: "LW",
      variantPresets: sizes,
    }),
    productWithVariants({
      id: 12,
      name: "Leather Biker Jacket",
      description: "Structured faux-leather jacket with asymmetric zip.",
      categoryId: 3,
      coverSeed: "fashion-biker-jacket",
      tags: ["limited"],
      basePrice: 129,
      skuPrefix: "LBJ",
      variantPresets: sizes,
    }),
    productWithVariants({
      id: 13,
      name: "Cargo Pants",
      description: "Relaxed cargo pants with adjustable cuffs and utility pockets.",
      categoryId: 4,
      coverSeed: "fashion-cargo-pants",
      gallerySeeds: ["fashion-cargo-pants-2"],
      tags: ["bestseller", "new"],
      basePrice: 69,
      skuPrefix: "CP",
      stockPattern: [12, 16, 14, 10, 6],
      variantPresets: sizes,
    }),
    productWithVariants({
      id: 14,
      name: "Slim Fit Chinos",
      description: "Stretch chinos with clean tapered leg.",
      categoryId: 4,
      coverSeed: "fashion-chinos",
      tags: ["essentials"],
      basePrice: 59,
      skuPrefix: "SFC",
      variantPresets: sizes,
    }),
    productWithVariants({
      id: 15,
      name: "Relaxed Joggers",
      description: "Soft terry joggers with elastic waist and cuffed hem.",
      categoryId: 4,
      coverSeed: "fashion-joggers",
      tags: ["new"],
      basePrice: 54,
      skuPrefix: "RJ",
      variantPresets: sizes,
    }),
    productWithVariants({
      id: 16,
      name: "Tailored Dress Pants",
      description: "Pressed front crease and refined drape for smart looks.",
      categoryId: 4,
      coverSeed: "fashion-dress-pants",
      tags: ["essentials"],
      basePrice: 74,
      skuPrefix: "TDP",
      variantPresets: sizes,
    }),
    productWithVariants({
      id: 17,
      name: "Athletic Shorts",
      description: "Quick-dry training shorts with inner brief liner.",
      categoryId: 5,
      coverSeed: "fashion-athletic-shorts",
      tags: ["new"],
      basePrice: 39,
      skuPrefix: "AS",
      variantPresets: sizes,
    }),
    productWithVariants({
      id: 18,
      name: "Denim Shorts",
      description: "Mid-rise denim shorts with raw hem detail.",
      categoryId: 5,
      coverSeed: "fashion-denim-shorts",
      tags: ["bestseller"],
      basePrice: 44,
      skuPrefix: "DS",
      variantPresets: sizes,
    }),
    productWithVariants({
      id: 19,
      name: "Linen Shorts",
      description: "Breathable linen blend for warm days.",
      categoryId: 5,
      coverSeed: "fashion-linen-shorts",
      tags: ["summer"],
      basePrice: 42,
      skuPrefix: "LS",
      variantPresets: sizes,
    }),
    productWithVariants({
      id: 20,
      name: "Canvas Tote Bag",
      description: "Durable canvas tote with interior pocket.",
      categoryId: 6,
      coverSeed: "fashion-tote-bag",
      tags: ["essentials"],
      basePrice: 28,
      skuPrefix: "CTB",
      variantPresets: ["One Size"],
      stockPattern: [40],
    }),
    productWithVariants({
      id: 21,
      name: "Leather Belt",
      description: "Full-grain leather belt with brushed buckle.",
      categoryId: 6,
      coverSeed: "fashion-leather-belt",
      tags: ["essentials"],
      basePrice: 35,
      skuPrefix: "LB",
      variantPresets: ["S", "M", "L", "XL"],
      stockPattern: [15, 20, 18, 10],
    }),
    productWithVariants({
      id: 22,
      name: "Knit Beanie",
      description: "Ribbed knit beanie in merino wool blend.",
      categoryId: 6,
      coverSeed: "fashion-knit-beanie",
      tags: ["new", "bestseller"],
      basePrice: 22,
      skuPrefix: "KB",
      variantPresets: ["One Size"],
      stockPattern: [50],
    }),
  ];
}

export function getPerfumeDemoCategories() {
  return [
    {
      id: 1,
      name: "Oud",
      slug: "oud",
      description: "Rich woody oud fragrances",
      image: null,
      sortOrder: 1,
      active: true,
    },
    {
      id: 2,
      name: "Floral",
      slug: "floral",
      description: "Elegant floral perfumes",
      image: null,
      sortOrder: 2,
      active: true,
    },
    {
      id: 3,
      name: "Citrus",
      slug: "citrus",
      description: "Fresh citrus blends",
      image: null,
      sortOrder: 3,
      active: true,
    },
    {
      id: 4,
      name: "Bestsellers",
      slug: "bestsellers",
      description: "Our most popular scents",
      image: null,
      sortOrder: 4,
      active: true,
    },
  ];
}

export function getPerfumeDemoProducts() {
  return [
    {
      id: 1,
      name: "Midnight Oud",
      description: "A rich woody fragrance with notes of oud, amber, and sandalwood.",
      coverImage: "https://picsum.photos/seed/midnight-oud/400/400",
      gallery: [
        "https://picsum.photos/seed/midnight-oud-2/400/400",
        "https://picsum.photos/seed/midnight-oud-3/400/400",
      ],
      categoryId: 1,
      variantType: "perfume-volume",
      variantLabel: "Volume",
      lowStockThreshold: 5,
      variants: [
        { label: "50ml", price: 45, stock: 12, sku: "MO-50" },
        { label: "100ml", price: 75, stock: 8, sku: "MO-100" },
      ],
      sizes: [
        { size: "50ml", price: 45, stock: 12, sku: "MO-50" },
        { size: "100ml", price: 75, stock: 8, sku: "MO-100" },
      ],
      tags: ["oud", "woody", "bestseller"],
    },
    {
      id: 2,
      name: "Rose Elixir",
      description: "Elegant floral perfume with Bulgarian rose and soft musk.",
      coverImage: "https://picsum.photos/seed/rose-elixir/400/400",
      gallery: ["https://picsum.photos/seed/rose-elixir-2/400/400"],
      categoryId: 2,
      variantType: "perfume-volume",
      variantLabel: "Volume",
      lowStockThreshold: 5,
      variants: [
        { label: "30ml", price: 35, stock: 20, sku: "RE-30" },
        { label: "50ml", price: 52, stock: 15, sku: "RE-50" },
        { label: "100ml", price: 89, stock: 10, sku: "RE-100" },
      ],
      sizes: [
        { size: "30ml", price: 35, stock: 20, sku: "RE-30" },
        { size: "50ml", price: 52, stock: 15, sku: "RE-50" },
        { size: "100ml", price: 89, stock: 10, sku: "RE-100" },
      ],
      tags: ["floral", "rose", "new"],
    },
    {
      id: 3,
      name: "Citrus Breeze",
      description: "Fresh citrus blend with bergamot, lemon, and white tea.",
      coverImage: "https://picsum.photos/seed/citrus-breeze/400/400",
      gallery: [],
      categoryId: 3,
      variantType: "perfume-volume",
      variantLabel: "Volume",
      lowStockThreshold: 5,
      variants: [
        { label: "50ml", price: 40, stock: 8, sku: "CB-50" },
        { label: "100ml", price: 68, stock: 25, sku: "CB-100" },
      ],
      sizes: [
        { size: "50ml", price: 40, stock: 8, sku: "CB-50" },
        { size: "100ml", price: 68, stock: 25, sku: "CB-100" },
      ],
      tags: ["citrus", "fresh", "summer"],
    },
    {
      id: 4,
      name: "Amber Noir",
      description: "Deep amber and vanilla with a smoky base.",
      coverImage: "https://picsum.photos/seed/amber-noir/400/400",
      gallery: ["https://picsum.photos/seed/amber-noir-2/400/400"],
      categoryId: 1,
      variantType: "perfume-volume",
      variantLabel: "Volume",
      lowStockThreshold: 5,
      variants: [
        { label: "50ml", price: 48, stock: 14, sku: "AN-50" },
        { label: "100ml", price: 82, stock: 6, sku: "AN-100" },
      ],
      sizes: [
        { size: "50ml", price: 48, stock: 14, sku: "AN-50" },
        { size: "100ml", price: 82, stock: 6, sku: "AN-100" },
      ],
      tags: ["oud", "bestseller"],
    },
    {
      id: 5,
      name: "Velvet Peony",
      description: "Soft peony and jasmine with a powdery finish.",
      coverImage: "https://picsum.photos/seed/velvet-peony/400/400",
      gallery: [],
      categoryId: 2,
      variantType: "perfume-volume",
      variantLabel: "Volume",
      lowStockThreshold: 5,
      variants: [
        { label: "30ml", price: 38, stock: 18, sku: "VP-30" },
        { label: "50ml", price: 55, stock: 12, sku: "VP-50" },
      ],
      sizes: [
        { size: "30ml", price: 38, stock: 18, sku: "VP-30" },
        { size: "50ml", price: 55, stock: 12, sku: "VP-50" },
      ],
      tags: ["floral", "bestseller"],
    },
  ];
}
